### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by aschwersenz** [ushahidi/opensourcedesign#14]
About hosting the website, where do you host your current sites? Can we also use that? Or should we come up with suggestions? Also who will handle the domain registration?

**Comment by aschwersenz** [comment]
from Justin: We'll handle the hosting and domain registrations. I'll get back to you with details

**Comment by justinscherer** [comment]
cc @tuxpiper

**Comment by tuxpiper** [comment]
What would  folks like to have? A custom built app or something more like a CMS?

In case it's a CMS (i.e. Wordpress, Craft..), I would suggest looking at services provided by experts hosting that exact CMS . They'll be more expensive than just paying for the servers , but that's because they take all the administrative overhead of keeping things running, updating versions, making backups, etc on them.

Most of these services, if they are good enough, allow bringing in your own personalized domain and may even take care of TLS/SSL (re: #19 ) by leveraging LetsEncrypt

**Comment by aschwersenz** [comment]
It is going to be a Wordpress. Do you already have experience with a service for that?

**Comment by tuxpiper** [comment]
> It is going to be a Wordpress. Do you already have experience with a service for that?

I don't have experience with any particular provider. There are lots of them (wordpress, bluehost, dreamhost and others come to mind).

When shopping for a managed solution, it helps to have a list of features that the project would like to have available, as well as any customizations that should be able to do on the setup. i.e. customize the themes, install plugins, etc .  Do we have something like that?

**Comment by aschwersenz** [comment]
Well, I can give you a quick overview:
_ We need to be able to install a custom theme
_ We have to be able to install plugins

The question of performance is something I can't really answer as I don't know how much traffic you are expecting, but my estimation for now would be that some cache plugin for WP is sufficient for now.

**Comment by Erioldoesdesign** [comment]
Completed! closing
